---
- name: Gather release versions
  metalstack.common.setup_yaml:

- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: yes
    that:
      - postgres_image_name is defined
      - postgres_image_tag is defined
      - postgres_backup_restore_sidecar_image_name is defined
      - postgres_backup_restore_sidecar_image_tag is defined

- name: Deploy postgres (backup-restore)
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'postgres.yaml.j2') }}"
    namespace: "{{ postgres_namespace }}"
