---
- name: Create haproxy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ image_cache_haproxy_host_dir_path }}/config"

- name: Template haproxy config
  ansible.builtin.template:
    src: haproxy.j2
    dest: "{{ image_cache_haproxy_host_dir_path }}/config/haproxy.cfg"
    owner: "root"
    group: "root"
    mode: "0755"
  register: result

- name: Deploy haproxy service
  ansible.builtin.include_role:
    name: metalstack.common.systemd_docker_service
  vars:
    systemd_service_name: haproxy
    systemd_docker_image_name: "{{ image_cache_haproxy_image_name }}"
    systemd_docker_image_tag: "{{ image_cache_haproxy_image_tag }}"
    systemd_external_config_changed: "{{ result is changed }}"
    systemd_docker_volumes:
      - "{{ image_cache_haproxy_host_dir_path }}/config:/usr/local/etc/haproxy:ro"
      - /etc/ssl/certs:/etc/ssl/certs:ro
    systemd_docker_ports:
      - host_port: "80"
        target_port: "8080"
      - host_port: "443"
        target_port: "8443"
      - host_port: "65534"
        target_port: "65534"
