---
- name: Gather release versions
  metalstack.common.setup_yaml:

- name: Create namespace {{ monitoring_namespace }}
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ monitoring_namespace }}"
        labels:
          name: "{{ monitoring_namespace }}"

- name: Deploy kube-prometheus-stack
  ansible.builtin.include_role:
    name: metalstack.common.helm_chart
  vars:
    helm_repo: "{{ prometheus_stack_repo }}"
    helm_chart: kube-prometheus-stack
    helm_target_namespace: "{{ monitoring_namespace }}"
    helm_release_name: kube-prometheus-stack
    helm_chart_version: "{{ prometheus_chart_version }}"
    helm_value_file_template: "prometheus-stack-values.yaml.j2"

- name: Deploy metrics exporters
  ansible.builtin.import_tasks: exporters.yaml

- name: Deploy Grafana dashboards
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'grafana-dashboards/' + item) }}"
    namespace: "{{ monitoring_namespace }}"
  loop:
    - machine-capacity.yaml.j2
    - metal-api.yaml.j2
    - rethinkdb.yaml.j2

- name: Create service monitors
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'servicemonitors/' + item) }}"
    namespace: "{{ monitoring_namespace }}"
  loop:
    - ipam-db.yaml.j2
    - masterdata-api.yaml.j2
    - masterdata-db.yaml.j2
    - metal-api.yaml.j2
    - metal-db.yaml.j2
    - metal-metrics-exporter.yaml.j2
