---
galaxy_info:
  role_name: postgres_backup_restore
  author: metal-stack
  description: Deploys a postgres database together with a backup-restore-sidecar.
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []

  platforms:
  - name: GenericLinux
    versions:
    - all

dependencies:
  - role: metalstack.common.defaults
  - role: metalstack.controlplane.defaults
