---
- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: true
    that:
      - dhcp_relay_server is not none

# config is written to /etc/default/isc-dhcp-relay

- name: Add dhcp relay interface
  ansible.builtin.command: net add dhcp relay interface {{ dhcp_relay_interface }}
  changed_when: false

- name: Remove priorly configured dhcp relay servers
  ansible.builtin.command: net del dhcp relay server
  changed_when: false

- name: Convert to list if dhcp_relay_server is only a string
  ansible.builtin.set_fact:
    _dhcp_relay_servers: "{{ [dhcp_relay_server] if dhcp_relay_server is string else dhcp_relay_server }}"

- name: Add dhcp relay server
  ansible.builtin.command: net add dhcp relay server {{ item }}
  loop: "{{ _dhcp_relay_servers }}"
  changed_when: false

- name: Commit configuration
  ansible.builtin.command: net commit
  register: result
  # shows a diff when something has changed, the diff contains a "@@"
  changed_when: "'@@' in result.stdout"
