---
- name: Gather release versions
  metalstack.common.setup_yaml:

- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: yes
    that:
      - nsq_image_name is defined
      - nsq_image_tag is defined

- name: Deploy nsq
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'nsq.yaml.j2') }}"
    namespace: "{{ metal_control_plane_namespace }}"
