---
galaxy_info:
  role_name: image_cache
  author: metal-stack
  description: This role is being used to deploy an image cache to a partition.
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []

  platforms:
  - name: Cumulus
    versions:
    - all
  - name: Debian
    versions:
    - all

dependencies:
  - role: metalstack.common.defaults
  - role: metalstack.partition.defaults
