---
- name: Gather release versions
  metalstack.common.setup_yaml:

- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: yes
    that:
      - metal_bmc_image_tag is defined
      - metal_bmc_image_name is defined
      - metal_bmc_bmc_superuser is defined
      - metal_bmc_bmc_superuser_pwd is defined
      - not metal_bmc_nsq_tls_enabled or (metal_bmc_nsq_tls_enabled and metal_bmc_nsqd_ca_cert is not none)
      - not metal_bmc_nsq_tls_enabled or (metal_bmc_nsq_tls_enabled and metal_bmc_nsqd_client_cert is not none)
      - metal_bmc_console_ca_cert is not none
      - metal_bmc_console_cert is not none
      - metal_bmc_console_key is not none

- name: Create nsq certs directory
  ansible.builtin.file:
    path: "{{ metal_bmc_nsq_cert_dir }}"
    state: directory
  when: metal_bmc_nsq_tls_enabled

- name: Copy nsq certificates
  ansible.builtin.copy:
    dest: "{{ metal_bmc_nsq_cert_dir }}/{{ item.filename }}"
    mode: 0640
    content: "{{ item.content }}"
  no_log: yes
  loop:
    - filename: ca.pem
      content: "{{ metal_bmc_nsqd_ca_cert }}"
    - filename: client.pem
      content: "{{ metal_bmc_nsqd_client_cert }}"
  loop_control:
    label: "{{ item.filename }}"
  when: metal_bmc_nsq_tls_enabled
  register: nsq_certs

- name: Create metal-bmc console certificates directory
  ansible.builtin.file:
    dest: "{{ metal_bmc_console_cert_dir }}"
    state: directory
    owner: "{{ metal_bmc_console_cert_owner }}"
    group: "{{ metal_bmc_console_cert_group }}"
    mode: 0700

- name: Copy metal-bmc console certificates
  ansible.builtin.copy:
    dest: "{{ metal_bmc_console_cert_dir }}/{{ item.filename }}"
    content: "{{ item.content }}"
    mode: 0640
    owner: "{{ metal_bmc_console_cert_owner }}"
    group: "{{ metal_bmc_console_cert_group }}"
  no_log: yes
  loop:
    - filename: ca.pem
      content: "{{ metal_bmc_console_ca_cert }}"
    - filename: cert.pem
      content: "{{ metal_bmc_console_cert }}"
    - filename: key.pem
      content: "{{ metal_bmc_console_key }}"
  loop_control:
    label: "{{ item.filename }}"

- name: Deploy metal-bmc service
  ansible.builtin.include_role:
    name: metalstack.common.systemd_docker_service
  vars:
    systemd_start: "{{ ensure_started.metal_bmc | default(true) }}"
    systemd_service_name: metal-bmc
    systemd_external_config_changed: "{{ nsq_certs is changed }}"
    systemd_docker_image_name: "{{ metal_bmc_image_name }}"
    systemd_docker_image_tag: "{{ metal_bmc_image_tag }}"
    systemd_docker_ports:
      - host_port: "{{ metal_bmc_console_port }}"
        target_port: "{{ metal_bmc_console_port }}"
    systemd_docker_volumes:
      - /var/lib/dhcp:/var/lib/dhcp:ro
      - /certs/nsq:/certs/nsq:ro
      - /certs/console:/certs/console:ro
    systemd_service_environment:
      TZ: "{{ metal_partition_timezone }}"
      METAL_BMC_LEASE_FILE: /var/lib/dhcp/dhcpd.leases
      METAL_BMC_PARTITION_ID: "{{ metal_partition_id }}"
      METAL_BMC_METAL_API_URL: "{{ metal_partition_metal_api_protocol }}://{{ metal_partition_metal_api_addr }}:{{ metal_partition_metal_api_port }}{{ metal_partition_metal_api_basepath }}"
      METAL_BMC_METAL_API_HMAC_KEY: "{{ metal_partition_metal_api_hmac_edit_key }}"
      METAL_BMC_IGNORE_MACS: "{{ metal_bmc_ignore_macs | join(',') }}"
      METAL_BMC_IPMI_USER: "{{ metal_bmc_bmc_superuser }}"
      METAL_BMC_IPMI_PASSWORD: "{{ metal_bmc_bmc_superuser_pwd }}"
      METAL_BMC_MQ_ADDRESS: "{{ metal_bmc_nsq_lookupd_addr }}"
      METAL_BMC_MQ_LOGLEVEL: "{{ metal_bmc_nsq_log_level }}"
      METAL_BMC_MQ_CA_CERT_FILE: "{{ metal_bmc_nsq_cert_dir }}/ca.pem"
      METAL_BMC_MQ_CLIENT_CERT_FILE: "{{ metal_bmc_nsq_cert_dir }}/client.pem"
      METAL_BMC_MACHINE_TOPIC: "{{ metal_partition_id }}-machine"
      METAL_BMC_CONSOLE_PORT: "{{ metal_bmc_console_port }}"
      METAL_BMC_CONSOLE_CA_CERT_FILE: "{{ metal_bmc_console_cert_dir }}/ca.pem"
      METAL_BMC_CONSOLE_CERT_FILE: "{{ metal_bmc_console_cert_dir }}/cert.pem"
      METAL_BMC_CONSOLE_KEY_FILE:  "{{ metal_bmc_console_cert_dir }}/key.pem"
