---
- name: Create namespace for metal stack
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ metal_control_plane_namespace }}"
        labels:
          name: "{{ metal_control_plane_namespace }}"
