---
- name: Check that the service file exists
  ansible.builtin.stat:
    path: /etc/systemd/system/{{ systemd_service_name }}.service
  register: systemd_service

- name: Ensure service is stopped
  ansible.builtin.systemd:
    name: "{{ systemd_service_name }}"
    state: stopped
    enabled: false
  when: systemd_service.stat.exists

- name: Remove service {{ systemd_service_name }}
  ansible.builtin.file:
    path: /etc/systemd/system/{{ systemd_service_name }}.service
    state: absent
