---
namespace: metalstack
name: common
version: 0.1.0
readme: README.md
authors:
- metal-stack
description: Ansible collection for providing common deployment parts for the metal-stack deployment.
license:
- MIT
license_file: '../LICENSE'
tags:
  - metalstack
dependencies: {}
repository: https://github.com/metal-stack/metal-ansible-collection
documentation: https://docs.metal-stack.io/
homepage: https://metal-stack.io/stable/
issues: https://github.com/metal-stack/metal-ansible-collection/issues

# A list of file glob-like patterns used to filter any files or directories that should not be included in the build
# artifact. A pattern is matched from the relative path of the file or directory of the collection directory. This
# uses 'fnmatch' to match the files or directories. Some directories and files like 'galaxy.yml', '*.pyc', '*.retry',
# and '.git' are always filtered
build_ignore: []
