---
- name: restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: reload frr
  ansible.builtin.service:
    name: frr
    enabled: true
    state: reloaded

- name: restart frr
  ansible.builtin.service:
    name: frr
    enabled: true
    state: restarted

- name: reload docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: reloaded

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: save iptables v4 rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  listen: persist iptables

- name: save iptables v6 rules
  ansible.builtin.shell: ip6tables-save > /etc/iptables/rules.v6
  listen: persist iptables
