---
- name: Add FRR apt-key to verify FRR package
  ansible.builtin.apt_key:
    url: https://deb-us.frrouting.org/frr/keys.asc
    state: present

- name: Add mainline FRR repository to install FRR
  ansible.builtin.apt_repository:
    repo: deb https://deb-us.frrouting.org/frr {{ ansible_distribution_release }} {{ mgmt_server_frr_repo }}
    state: present
    filename: frr.list

- name: Install required packages to have the network stack in place
  ansible.builtin.apt:
    name:
    - frr={{ mgmt_server_frr_version }}*
    - frr-pythontools={{ mgmt_server_frr_version }}*
    update_cache: yes
    force_apt_get: yes

- name: Enable bgp daemons required to run bgp
  ansible.builtin.copy:
    src: daemons
    dest: /etc/frr/daemons
    mode: 0640
  notify: restart frr
