name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/metal-stack/metal-deployment-base:latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          make install
          make unit
          make molecule
