---
- name: Create logical volume
  community.general.system.lvol:
    vg: "{{ lvm_vg }}"
    lv: "{{ lv.name }}"
    size: "{{ lv.size }}"
    opts: "{{ lv.opts | default('') }}"
    resizefs: yes

- name: Create filesystem
  community.general.system.filesystem:
    fstype: "{{ lv.fstype }}"
    dev: "/dev/{{ lvm_vg }}/{{ lv.name }}"

- name: Create mountpath
  ansible.builtin.file:
    path: "{{ lv.mountpath }}"
    state: directory
    mode: 0750

- name: Mount logical volume
  ansible.posix.mount:
    path: "{{ lv.mountpath }}"
    src: "/dev/{{ lvm_vg }}/{{ lv.name }}"
    fstype: "{{ lv.fstype }}"
    opts: defaults
    state: mounted
