---
- name: Check mandatory variables for this role are set
  ansible.builtin.assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: yes
    that:
      - lvm_vg is not none
      - lvm_pvs is not none
      - lvm_lvs is not none

- name: Create volumegroup
  lvg:
    vg: "{{ lvm_vg }}"
    pvs: "{{ lvm_pvs }}"

- name: Create logical volumes
  include_tasks: lv.yaml
  loop: "{{ lvm_lvs }}"
  loop_control:
    loop_var: lv
